### ISSUE TITLE
When statistics data is out of date, an SNMP client gets confusing query results

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-snmp-handlers#34]
When statistics are out of date, the SNMP agent tells the requesting client that no such OID exists; which isn't actually true (example below). It exists, but there's no valid data for it. My experience has been that an  agent would return an invalid value (e.g. maximum integer or similar) under such a condition.
```
$ snmpwalk -v2c -c clearwater <host> 1.2.826.0.1.1578918.9
iso.2.826.0.1.1578918.9 = No Such Object available on this agent at this OID
```
BTW - Here's the typical syslog entry from the agent during this condition:
```
homestead-1 homestead_handler[28438]: Ignoring request because data out of date (1420824036 ? 0)
```

**Comment by mirw** [comment]
Related to https://github.com/Metaswitch/clearwater-snmp-handlers/issues/28?

**Comment by dtheobald** [comment]
Yes, it's similar the #28, but this one is just a general comment about the fact that the SNMP statistic handler makes it look like the OID doesn't exist when no valid data is available; which is confusing since the OID actually still exists. In my experience OIDs like these don't come and go based on validity of data, they typically would return a published invalid value instead.

**Comment by mirw** [comment]
I think the question is why the OID is invalid.

*   If there is no value because there is no sprout process (for example), I think it's reasonable for there to be no OID.  (Consider the model in which the SNMP agent is embedded in that process - in that case, you wouldn't get back a special out-of-range value - you'd either get no value or you'd get an error back.)  You're right that this isn't covered by #28, but I think our current behavior is correct.

*   If there is no value because we're only caching it for x seconds and we haven't had an update in that period (as covered by #28), you're right that we should return an actual value, but in that case I think we can (and should) return the correct value.

Does this address your concern?  In which situation(s) do you think we should return a published invalid value?

**Comment by dtheobald** [comment]
Yes, I agree with both your points.

**Comment by mirw** [comment]
Thanks!

OK, so I think bullet 2 is covered by #28 (feel free to update that issue if it needs clarification).  Can we close this one?
