### ISSUE TITLE
Some alarms are thrown way on boot because snmpd/alarm-agent isn't up yet

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-snmp-handlers#96]
On boot I see messages like this in syslog:
```
dropped request: 'issue-alarm cluster-manager 8001.4'
```

I also see the alarm-agent getting a zmq_bind error (```No such file or directory```) on ```ipc:///var/run/clearwater/alarms```. My workaround code of having the alarm-agent kill itself prevents the alarm-agent from being stuck in that state, but it's worth someone else taking a look at why it (sometimes) gets that error when 0MQ is supposed to create the socket (and does at other times). I didn't have the time to get to the bottom of it, hence the workaround.

Diags are available

**Comment by eleanor-merry** [comment]
How many alarm processes are running on your node? The alarms process doesn't currently have no-start set in the debian rules, so there's a chance that monit can lose track of it. Two processes trying to bind (and remove!) the socket file can cause these symptoms

**Comment by dtheobald** [comment]
No, there's only one running.

**Comment by mirw** [comment]
@dtheobald, I think the next action here is to back out your hack and reproduce.  As it is, the diagnostics don't seem to show anything interesting because the problem has already been resolved.  Is that OK?

**Comment by dtheobald** [comment]
Reopened because the alarm agent still sees ```zmq_bind``` failures during boot which causes it to completely malfunction (i.e. process no alarms) requiring human intervention to correct.

I took a closer look and have made some improvements to my fix (e.g. retrying zmq_bind before abandoning), but am not planning to spend anymore time on this due to the lack of visibility into 0MQ and I don't think it's worth anymore time because the code should handle ```zmq_bind``` errors anyway. If you're interested in my fix to ```alarm_req_listener.cpp```, let me know and I'll pass it along to you.

**Comment by rkd-msw** [comment]
I've taken a look at this and think I've traced out the failure path.

* clearwater-snmp-alarm-agent starts when /var/run/clearwater doesn't exist (possibly on initial install?)
* zmq_bind tries to create the /var/run/clearwater/alarms socket, but this fails with ENOENT because the containing directory (/var/run/clearwater) doesn't exist
* this causes the call to zmq_init_sck to fail, but zmq_init_sck is called from the ZMQ listener thread, so it just causes that thread to fail
* failures in the ZMQ listener thread don't cause the main process to exit, so the process stays running but doesn't process alarms

I'm going to make three or four fixes to correct this:
* the alarm agent should create /var/run/clearwater before trying to bind /var/run/clearwater/alarms
* zmq_init_sck should run when AlarmReqListener::start() is called, not on the listener thread
* we should pass the termination semaphore to AlarmReqListener::start(), so that when the listener thread exits (e.g. if /var/run/clearwater/alarms gets deleted while it's running so zmq_msg_recv returns ENOTSOCK), it can call that and cleanly shut down the main thread
* it might be possible for Monit to send a poll over the ZMQ socket, as an extra way of confirming that the listener thread is working

@dtheobald - if any of those sound like fixes you've already made, feel free to send them across, as that might save time.

**Comment by rkd-msw** [comment]
I've made the first three fixes - I'll open a separate issue to cover Monit polling. This is now ready for retest.

**Comment by dtheobald** [comment]
Fixed
